research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

writer_task:
  description: >
    Review the context you got and create a 5 to 10 line poem incorporating at least 3 of the
    facts from the research
  expected_output: >
    a poem that is 5 to 10 lines long.
  agent: poem_writer
